"""
Detection Rule Specifications for ECDAT Source Code Cryptographic Scanner.

Rule ID Convention:
  {LANG}-{LIB/DOMAIN}-{ALGORITHM}-{NNN}

  e.g. PY-HASHLIB-MD5-001, JS-WEBCRYPTO-AES-001, GO-CRYPTO-RSA-001
"""

import re
from dataclasses import dataclass
from typing import Optional, List, Set, Union


@dataclass
class RegexRule:
    rule_id: str
    name: str
    language: str  # 'python', 'java', 'c', 'cpp', 'javascript', 'typescript', 'go', 'rust', 'php', 'csharp', 'kotlin', 'pem', 'config', 'all'
    pattern: re.Pattern
    algorithm: str
    category: str
    library: str
    confidence: float = 0.80
    key_length: Optional[int] = None
    mode: Optional[str] = None
    padding: Optional[str] = None
    purpose: Optional[str] = None          # e.g. 'hashing', 'encryption', 'signing', 'key_generation', 'unknown'
    protocol: Optional[str] = None         # e.g. 'TLS', 'SSH', 'JWT'
    secret_name_group: Optional[int] = None
    secret_value_group: Optional[int] = None


_IDENTIFIER_TOKEN_RE = re.compile(r"[A-Z]+(?=[A-Z]|$)|[A-Z]?[a-z]+|\d+")
_SENSITIVE_NAME_TOKENS: Set[str] = {
    "key",
    "secret",
    "password",
    "passwd",
    "pwd",
    "token",
}
_BENIGN_NAME_TOKENS: Set[str] = {
    "algorithm",
    "algo",
    "count",
    "dummy",
    "example",
    "fake",
    "file",
    "hint",
    "id",
    "identifier",
    "label",
    "length",
    "name",
    "not",
    "path",
    "policy",
    "public",
    "sample",
    "size",
    "uri",
    "url",
}
_STRING_LITERAL_RE = re.compile(r"""([bBrRuUfF]*)(["'])(?:\\.|(?!\2).)*\2""")


def _identifier_tokens(identifier: str) -> Set[str]:
    normalized = re.sub(r"[^A-Za-z0-9]+", " ", identifier)
    tokens: Set[str] = set()
    for part in normalized.split():
        tokens.update(match.group(0).lower() for match in _IDENTIFIER_TOKEN_RE.finditer(part))
    return tokens


def is_hardcoded_secret_candidate(identifier: str, literal_value: Union[str, bytes]) -> bool:
    """Return True for explicit secret-looking identifiers assigned static literals."""
    tokens = _identifier_tokens(identifier)
    if not tokens.intersection(_SENSITIVE_NAME_TOKENS):
        return False
    if tokens.intersection(_BENIGN_NAME_TOKENS):
        return False

    if isinstance(literal_value, bytes):
        try:
            value = literal_value.decode("utf-8")
        except UnicodeDecodeError:
            value = literal_value.hex()
    else:
        value = str(literal_value)

    if len(value) < 12:
        return False
    if any(ch.isspace() for ch in value):
        return False
    if value.lower().startswith(("http://", "https://", "file:")):
        return False
    if len(set(value)) < 4:
        return False
    if not any(ch.isalpha() for ch in value):
        return False

    return True


def redact_secret_literal(snippet: str) -> str:
    """Redact the first literal in a hardcoded secret assignment evidence snippet."""
    return _STRING_LITERAL_RE.sub(
        lambda match: f"{match.group(1)}{match.group(2)}***REDACTED***{match.group(2)}",
        snippet,
        count=1,
    )


# Language specific and general regex detection rules
REGEX_RULES: List[RegexRule] = [

    # ═══════════════════════════════════════════════════════════════
    # PYTHON RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="PY-HASHLIB-MD5-001",
        name="Python hashlib MD5",
        language="python",
        pattern=re.compile(r"\bhashlib\.md5\s*\("),
        algorithm="MD5",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-SHA1-001",
        name="Python hashlib SHA-1",
        language="python",
        pattern=re.compile(r"\bhashlib\.sha1\s*\("),
        algorithm="SHA-1",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-SHA224-001",
        name="Python hashlib SHA-224",
        language="python",
        pattern=re.compile(r"\bhashlib\.sha224\s*\("),
        algorithm="SHA-224",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-SHA256-001",
        name="Python hashlib SHA-256",
        language="python",
        pattern=re.compile(r"\bhashlib\.sha256\s*\("),
        algorithm="SHA-256",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-SHA384-001",
        name="Python hashlib SHA-384",
        language="python",
        pattern=re.compile(r"\bhashlib\.sha384\s*\("),
        algorithm="SHA-384",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-SHA512-001",
        name="Python hashlib SHA-512",
        language="python",
        pattern=re.compile(r"\bhashlib\.sha512\s*\("),
        algorithm="SHA-512",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-SHA3-001",
        name="Python hashlib SHA-3",
        language="python",
        pattern=re.compile(r"\bhashlib\.sha3_(256|512)\s*\("),
        algorithm="SHA-3",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-BLAKE2-001",
        name="Python hashlib BLAKE2",
        language="python",
        pattern=re.compile(r"\bhashlib\.blake2[bs]\s*\("),
        algorithm="BLAKE2",
        category="hashing",
        library="hashlib",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-PYCRYPTO-RSA-GENERATE-001",
        name="Python PyCryptodome RSA Generate",
        language="python",
        pattern=re.compile(r"\bRSA\.generate\s*\(\s*(\d+)"),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="PyCryptodome",
        confidence=0.80,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="PY-PYCRYPTO-AES-NEW-001",
        name="Python PyCryptodome AES New",
        language="python",
        pattern=re.compile(r"\bAES\.new\s*\("),
        algorithm="AES",
        category="symmetric_encryption",
        library="PyCryptodome",
        confidence=0.80,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PY-PYCRYPTO-DES3-001",
        name="Python PyCryptodome Triple DES",
        language="python",
        pattern=re.compile(r"\bDES3\.new\s*\("),
        algorithm="3DES",
        category="symmetric_encryption",
        library="PyCryptodome",
        confidence=0.80,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PY-PYCRYPTO-DES-001",
        name="Python PyCryptodome DES",
        language="python",
        pattern=re.compile(r"\bDES\.new\s*\("),
        algorithm="DES",
        category="symmetric_encryption",
        library="PyCryptodome",
        confidence=0.80,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PY-PYCRYPTO-ARC4-001",
        name="Python PyCryptodome ARC4 (RC4)",
        language="python",
        pattern=re.compile(r"\bARC4\.new\s*\("),
        algorithm="RC4",
        category="symmetric_encryption",
        library="PyCryptodome",
        confidence=0.80,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PY-PYCRYPTO-CHACHA20-001",
        name="Python PyCryptodome ChaCha20",
        language="python",
        pattern=re.compile(r"\bChaCha20(?:_Poly1305)?\.new\s*\("),
        algorithm="ChaCha20",
        category="symmetric_encryption",
        library="PyCryptodome",
        confidence=0.85,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-SHA1-001",
        name="Python Cryptography SHA-1",
        language="python",
        pattern=re.compile(r"\bhashes\.SHA1\s*\(\s*\)"),
        algorithm="SHA-1",
        category="hashing",
        library="cryptography",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-SHA256-001",
        name="Python Cryptography SHA-256",
        language="python",
        pattern=re.compile(r"\bhashes\.SHA256\s*\(\s*\)"),
        algorithm="SHA-256",
        category="hashing",
        library="cryptography",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-SHA512-001",
        name="Python Cryptography SHA-512",
        language="python",
        pattern=re.compile(r"\bhashes\.SHA512\s*\(\s*\)"),
        algorithm="SHA-512",
        category="hashing",
        library="cryptography",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-SHA3-001",
        name="Python Cryptography SHA3",
        language="python",
        pattern=re.compile(r"\bhashes\.SHA3_(?:224|256|384|512)\s*\(\s*\)"),
        algorithm="SHA-3",
        category="hashing",
        library="cryptography",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-MD5-001",
        name="Python Cryptography MD5",
        language="python",
        pattern=re.compile(r"\bhashes\.MD5\s*\(\s*\)"),
        algorithm="MD5",
        category="hashing",
        library="cryptography",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-CBC-001",
        name="Python Cryptography Mode CBC",
        language="python",
        pattern=re.compile(r"\bmodes\.CBC\s*\("),
        algorithm="AES",
        category="symmetric_encryption",
        library="cryptography",
        confidence=0.80,
        mode="CBC",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-GCM-001",
        name="Python Cryptography Mode GCM",
        language="python",
        pattern=re.compile(r"\bmodes\.GCM\s*\("),
        algorithm="AES",
        category="symmetric_encryption",
        library="cryptography",
        confidence=0.80,
        mode="GCM",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-RSA-GENERATE-001",
        name="Python Cryptography RSA Generate",
        language="python",
        pattern=re.compile(r"\brsa\.generate_private_key\s*\("),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="cryptography",
        confidence=0.90,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-EC-GENERATE-001",
        name="Python Cryptography EC Generate",
        language="python",
        pattern=re.compile(r"\bec\.generate_private_key\s*\("),
        algorithm="ECC",
        category="asymmetric_encryption",
        library="cryptography",
        confidence=0.90,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-ECDSA-001",
        name="Python Cryptography ECDSA Sign",
        language="python",
        pattern=re.compile(r"\.sign\s*\([^)]*ECDSA\s*\("),
        algorithm="ECDSA",
        category="digital_signature",
        library="cryptography",
        confidence=0.85,
        purpose="signing",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-HMAC-001",
        name="Python Cryptography HMAC",
        language="python",
        pattern=re.compile(r"\bhmac\.HMAC\s*\("),
        algorithm="HMAC",
        category="mac",
        library="cryptography",
        confidence=0.85,
        purpose="mac",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-HMAC-001",
        name="Python hashlib HMAC",
        language="python",
        pattern=re.compile(r"\bhmac\.new\s*\("),
        algorithm="HMAC",
        category="mac",
        library="hmac",
        confidence=0.80,
        purpose="mac",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-PBKDF2-001",
        name="Python Cryptography PBKDF2HMAC",
        language="python",
        pattern=re.compile(r"\bPBKDF2HMAC\s*\("),
        algorithm="PBKDF2",
        category="key_derivation",
        library="cryptography",
        confidence=0.90,
        purpose="key_derivation",
    ),
    RegexRule(
        rule_id="PY-CRYPTOGRAPHY-SCRYPT-001",
        name="Python Cryptography Scrypt",
        language="python",
        pattern=re.compile(r"\bScrypt\s*\("),
        algorithm="scrypt",
        category="key_derivation",
        library="cryptography",
        confidence=0.90,
        purpose="key_derivation",
    ),
    RegexRule(
        rule_id="PY-JWT-ENCODE-001",
        name="Python JWT encode",
        language="python",
        pattern=re.compile(r"\bjwt\.encode\s*\("),
        algorithm="JWT",
        category="protocol",
        library="PyJWT",
        confidence=0.80,
        purpose="unknown",
        protocol="JWT",
    ),
    RegexRule(
        rule_id="PY-HASHLIB-HARDCODED-001",
        name="Python Hardcoded Secret Assignment",
        language="python",
        pattern=re.compile(
            r'\b([A-Za-z_][A-Za-z0-9_]*)\s*(?::\s*(?:str|bytes))?\s*=\s*([bBrR]*["\'])([^"\'\\]{12,})["\']'
        ),
        algorithm="SECRET",
        category="hardcoded_secret",
        library="source-code",
        confidence=0.70,
        purpose="unknown",
        secret_name_group=1,
        secret_value_group=3,
    ),

    # ═══════════════════════════════════════════════════════════════
    # JAVA RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="JAVA-JCE-CIPHER-001",
        name="Java Cipher getInstance",
        language="java",
        pattern=re.compile(r'\bCipher\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="AES",  # Dynamically parsed in scanner
        category="symmetric_encryption",
        library="javax.crypto",
        confidence=0.80,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="JAVA-JCE-KEYPAIRGEN-001",
        name="Java KeyPairGenerator getInstance",
        language="java",
        pattern=re.compile(r'\bKeyPairGenerator\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="RSA",  # Dynamically parsed
        category="asymmetric_encryption",
        library="java.security",
        confidence=0.80,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="JAVA-JCE-MESSAGEDIGEST-001",
        name="Java MessageDigest getInstance",
        language="java",
        pattern=re.compile(r'\bMessageDigest\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="SHA-256",  # Dynamically parsed
        category="hashing",
        library="java.security",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="JAVA-JCE-SIGNATURE-001",
        name="Java Signature getInstance",
        language="java",
        pattern=re.compile(r'\bSignature\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="Signature",  # Dynamically parsed
        category="digital_signature",
        library="java.security",
        confidence=0.80,
        purpose="signing",
    ),
    RegexRule(
        rule_id="JAVA-JCE-KEYAGREEMENT-001",
        name="Java KeyAgreement getInstance",
        language="java",
        pattern=re.compile(r'\bKeyAgreement\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="ECDH",  # Dynamically parsed
        category="key_exchange",
        library="javax.crypto",
        confidence=0.80,
        purpose="key_exchange",
    ),
    RegexRule(
        rule_id="JAVA-JCE-MAC-001",
        name="Java Mac getInstance (HMAC)",
        language="java",
        pattern=re.compile(r'\bMac\.getInstance\s*\(\s*"(Hmac[A-Z0-9]+)"\s*\)'),
        algorithm="HMAC",
        category="mac",
        library="javax.crypto",
        confidence=0.80,
        purpose="mac",
    ),
    RegexRule(
        rule_id="JAVA-JCE-SECRETKEYFACTORY-001",
        name="Java SecretKeyFactory PBKDF2",
        language="java",
        pattern=re.compile(r'\bSecretKeyFactory\.getInstance\s*\(\s*"(PBKDF2[^"]+)"\s*\)'),
        algorithm="PBKDF2",
        category="key_derivation",
        library="javax.crypto",
        confidence=0.85,
        purpose="key_derivation",
    ),
    RegexRule(
        rule_id="JAVA-HARDCODED-SECRET-001",
        name="Java Hardcoded Secret String",
        language="java",
        pattern=re.compile(
            r'\b(?:(?:public|private|protected|static|final)\s+)*'
            r'String\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*"([^"\r\n]{12,})"'
        ),
        algorithm="SECRET",
        category="hardcoded_secret",
        library="source-code",
        confidence=0.70,
        purpose="unknown",
        secret_name_group=1,
        secret_value_group=2,
    ),

    # ═══════════════════════════════════════════════════════════════
    # C / C++ RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="C-OPENSSL-RSA-GENERATE-001",
        name="C/C++ OpenSSL RSA Generate Key",
        language="c",
        pattern=re.compile(r"\bRSA_generate_key_ex\s*\("),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="OpenSSL",
        confidence=0.80,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="C-OPENSSL-AES128-CBC-001",
        name="C/C++ OpenSSL EVP AES-128-CBC",
        language="c",
        pattern=re.compile(r"\bEVP_aes_128_cbc\s*\("),
        algorithm="AES",
        category="symmetric_encryption",
        library="OpenSSL",
        confidence=0.80,
        key_length=128,
        mode="CBC",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="C-OPENSSL-AES256-GCM-001",
        name="C/C++ OpenSSL EVP AES-256-GCM",
        language="c",
        pattern=re.compile(r"\bEVP_aes_256_gcm\s*\("),
        algorithm="AES",
        category="symmetric_encryption",
        library="OpenSSL",
        confidence=0.80,
        key_length=256,
        mode="GCM",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="C-OPENSSL-AES256-CBC-001",
        name="C/C++ OpenSSL EVP AES-256-CBC",
        language="c",
        pattern=re.compile(r"\bEVP_aes_256_cbc\s*\("),
        algorithm="AES",
        category="symmetric_encryption",
        library="OpenSSL",
        confidence=0.80,
        key_length=256,
        mode="CBC",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="C-OPENSSL-AES128-GCM-001",
        name="C/C++ OpenSSL EVP AES-128-GCM",
        language="c",
        pattern=re.compile(r"\bEVP_aes_128_gcm\s*\("),
        algorithm="AES",
        category="symmetric_encryption",
        library="OpenSSL",
        confidence=0.80,
        key_length=128,
        mode="GCM",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="C-OPENSSL-SHA256-001",
        name="C/C++ OpenSSL EVP SHA-256",
        language="c",
        pattern=re.compile(r"\bEVP_sha256\s*\("),
        algorithm="SHA-256",
        category="hashing",
        library="OpenSSL",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="C-OPENSSL-SHA512-001",
        name="C/C++ OpenSSL EVP SHA-512",
        language="c",
        pattern=re.compile(r"\bEVP_sha512\s*\("),
        algorithm="SHA-512",
        category="hashing",
        library="OpenSSL",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="C-OPENSSL-SHA1-001",
        name="C/C++ OpenSSL EVP SHA-1",
        language="c",
        pattern=re.compile(r"\bEVP_sha1\s*\("),
        algorithm="SHA-1",
        category="hashing",
        library="OpenSSL",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="C-OPENSSL-MD5-001",
        name="C/C++ OpenSSL EVP MD5",
        language="c",
        pattern=re.compile(r"\bEVP_md5\s*\("),
        algorithm="MD5",
        category="hashing",
        library="OpenSSL",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="C-OPENSSL-EC-NEW-001",
        name="C/C++ OpenSSL EC Key New",
        language="c",
        pattern=re.compile(r"\bEC_KEY_new_by_curve_name\s*\("),
        algorithm="ECC",
        category="asymmetric_encryption",
        library="OpenSSL",
        confidence=0.80,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="C-OPENSSL-DH-NEW-001",
        name="C/C++ OpenSSL DH New",
        language="c",
        pattern=re.compile(r"\bDH_new\s*\("),
        algorithm="DH",
        category="key_exchange",
        library="OpenSSL",
        confidence=0.80,
        purpose="key_exchange",
    ),
    RegexRule(
        rule_id="C-OPENSSL-DSA-NEW-001",
        name="C/C++ OpenSSL DSA New",
        language="c",
        pattern=re.compile(r"\bDSA_new\s*\("),
        algorithm="DSA",
        category="digital_signature",
        library="OpenSSL",
        confidence=0.80,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="C-OPENSSL-HMAC-001",
        name="C/C++ OpenSSL HMAC",
        language="c",
        pattern=re.compile(r"\bHMAC\s*\("),
        algorithm="HMAC",
        category="mac",
        library="OpenSSL",
        confidence=0.80,
        purpose="mac",
    ),
    RegexRule(
        rule_id="C-OPENSSL-EVP-PKEY-SIGN-001",
        name="C/C++ OpenSSL EVP_PKEY Sign",
        language="c",
        pattern=re.compile(r"\bEVP_DigestSignInit\s*\("),
        algorithm="RSA",
        category="digital_signature",
        library="OpenSSL",
        confidence=0.80,
        purpose="signing",
    ),
    RegexRule(
        rule_id="C-HARDCODED-SECRET-001",
        name="C/C++ Hardcoded Secret String",
        language="c",
        pattern=re.compile(
            r'\b(?:static\s+)?(?:const\s+)?(?:char\s*(?:\*+\s*)+|char\s+)'
            r'([A-Za-z_][A-Za-z0-9_]*)(?:\[[^\]]*\])?'
            r'\s*=\s*"([^"\r\n]{12,})"'
        ),
        algorithm="SECRET",
        category="hardcoded_secret",
        library="source-code",
        confidence=0.70,
        purpose="unknown",
        secret_name_group=1,
        secret_value_group=2,
    ),

    # ═══════════════════════════════════════════════════════════════
    # JAVASCRIPT / TYPESCRIPT RULES
    # ═══════════════════════════════════════════════════════════════

    # Web Crypto API (browser & Node.js): window.crypto.subtle / crypto.subtle
    RegexRule(
        rule_id="JS-WEBCRYPTO-GENERATE-001",
        name="JS/TS WebCrypto generateKey",
        language="javascript",
        pattern=re.compile(r'\.generateKey\s*\(\s*\{[^}]*"name"\s*:\s*"([^"]+)"'),
        algorithm="AES",  # Dynamically parsed
        category="symmetric_encryption",
        library="WebCrypto",
        confidence=0.85,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="JS-WEBCRYPTO-ENCRYPT-001",
        name="JS/TS WebCrypto encrypt",
        language="javascript",
        pattern=re.compile(r'\.encrypt\s*\(\s*\{\s*"?name"?\s*:\s*"([^"]+)"'),
        algorithm="AES",  # Dynamically parsed
        category="symmetric_encryption",
        library="WebCrypto",
        confidence=0.85,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="JS-WEBCRYPTO-DIGEST-001",
        name="JS/TS WebCrypto digest (hash)",
        language="javascript",
        pattern=re.compile(r'\.digest\s*\(\s*"(SHA-(?:1|256|384|512))"'),
        algorithm="SHA-256",  # Dynamically parsed from group 1
        category="hashing",
        library="WebCrypto",
        confidence=0.85,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="JS-WEBCRYPTO-SIGN-001",
        name="JS/TS WebCrypto sign",
        language="javascript",
        pattern=re.compile(r'\.sign\s*\(\s*\{\s*"?name"?\s*:\s*"(RSASSA-PKCS1-v1_5|ECDSA|RSA-PSS|Ed25519)"'),
        algorithm="ECDSA",  # Dynamically parsed
        category="digital_signature",
        library="WebCrypto",
        confidence=0.85,
        purpose="signing",
    ),
    RegexRule(
        rule_id="JS-CRYPTO-NODE-CREATEHASH-001",
        name="JS/TS Node.js crypto createHash",
        language="javascript",
        pattern=re.compile(r'\bcrypto\.createHash\s*\(\s*["\']([^"\']+)["\']'),
        algorithm="SHA-256",  # Dynamically parsed
        category="hashing",
        library="node:crypto",
        confidence=0.85,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="JS-CRYPTO-NODE-CREATECIPHER-001",
        name="JS/TS Node.js crypto createCipheriv",
        language="javascript",
        pattern=re.compile(r'\bcrypto\.createCipheriv\s*\(\s*["\']([^"\']+)["\']'),
        algorithm="AES",  # Dynamically parsed
        category="symmetric_encryption",
        library="node:crypto",
        confidence=0.85,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="JS-CRYPTO-NODE-HMAC-001",
        name="JS/TS Node.js crypto createHmac",
        language="javascript",
        pattern=re.compile(r'\bcrypto\.createHmac\s*\(\s*["\']([^"\']+)["\']'),
        algorithm="HMAC",
        category="mac",
        library="node:crypto",
        confidence=0.85,
        purpose="mac",
    ),
    RegexRule(
        rule_id="JS-CRYPTO-NODE-GENKEYPAIR-001",
        name="JS/TS Node.js crypto generateKeyPair",
        language="javascript",
        pattern=re.compile(r'\bcrypto\.generateKeyPair(?:Sync)?\s*\(\s*["\']([^"\']+)["\']'),
        algorithm="RSA",  # Dynamically parsed
        category="asymmetric_encryption",
        library="node:crypto",
        confidence=0.85,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="JS-JWT-SIGN-001",
        name="JS/TS JWT sign",
        language="javascript",
        pattern=re.compile(r'\bjwt\.sign\s*\('),
        algorithm="JWT",
        category="protocol",
        library="jsonwebtoken",
        confidence=0.80,
        purpose="signing",
        protocol="JWT",
    ),
    RegexRule(
        rule_id="JS-FORGE-RSA-001",
        name="JS/TS node-forge RSA",
        language="javascript",
        pattern=re.compile(r'\bforge\.pki\.rsa\.generateKeyPair\s*\('),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="node-forge",
        confidence=0.85,
        purpose="key_generation",
    ),

    # ═══════════════════════════════════════════════════════════════
    # GO RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="GO-CRYPTO-RSA-GENERATE-001",
        name="Go crypto/rsa GenerateKey",
        language="go",
        pattern=re.compile(r'\brsa\.GenerateKey\s*\('),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="crypto/rsa",
        confidence=0.90,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-ECDSA-GENERATE-001",
        name="Go crypto/ecdsa GenerateKey",
        language="go",
        pattern=re.compile(r'\becdsa\.GenerateKey\s*\('),
        algorithm="ECDSA",
        category="digital_signature",
        library="crypto/ecdsa",
        confidence=0.90,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-ED25519-GENERATE-001",
        name="Go crypto/ed25519 GenerateKey",
        language="go",
        pattern=re.compile(r'\bed25519\.GenerateKey\s*\('),
        algorithm="Ed25519",
        category="digital_signature",
        library="crypto/ed25519",
        confidence=0.90,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-AES-NEW-001",
        name="Go crypto/aes NewCipher",
        language="go",
        pattern=re.compile(r'\baes\.NewCipher\s*\('),
        algorithm="AES",
        category="symmetric_encryption",
        library="crypto/aes",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-DES-NEW-001",
        name="Go crypto/des NewCipher",
        language="go",
        pattern=re.compile(r'\bdes\.NewCipher\s*\('),
        algorithm="DES",
        category="symmetric_encryption",
        library="crypto/des",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-3DES-NEW-001",
        name="Go crypto/des NewTripleDESCipher",
        language="go",
        pattern=re.compile(r'\bdes\.NewTripleDESCipher\s*\('),
        algorithm="3DES",
        category="symmetric_encryption",
        library="crypto/des",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-RC4-NEW-001",
        name="Go crypto/rc4 NewCipher",
        language="go",
        pattern=re.compile(r'\brc4\.NewCipher\s*\('),
        algorithm="RC4",
        category="symmetric_encryption",
        library="crypto/rc4",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-SHA256-001",
        name="Go crypto/sha256 New",
        language="go",
        pattern=re.compile(r'\bsha256\.New\s*\(\s*\)'),
        algorithm="SHA-256",
        category="hashing",
        library="crypto/sha256",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-SHA512-001",
        name="Go crypto/sha512 New",
        language="go",
        pattern=re.compile(r'\bsha512\.New\s*\(\s*\)'),
        algorithm="SHA-512",
        category="hashing",
        library="crypto/sha512",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-SHA1-001",
        name="Go crypto/sha1 New",
        language="go",
        pattern=re.compile(r'\bsha1\.New\s*\(\s*\)'),
        algorithm="SHA-1",
        category="hashing",
        library="crypto/sha1",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-MD5-001",
        name="Go crypto/md5 New",
        language="go",
        pattern=re.compile(r'\bmd5\.New\s*\(\s*\)'),
        algorithm="MD5",
        category="hashing",
        library="crypto/md5",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-HMAC-001",
        name="Go crypto/hmac New",
        language="go",
        pattern=re.compile(r'\bhmac\.New\s*\('),
        algorithm="HMAC",
        category="mac",
        library="crypto/hmac",
        confidence=0.90,
        purpose="mac",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-GCM-001",
        name="Go cipher.NewGCM",
        language="go",
        pattern=re.compile(r'\bcipher\.NewGCM\s*\('),
        algorithm="AES",
        category="symmetric_encryption",
        library="crypto/cipher",
        confidence=0.85,
        mode="GCM",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-DH-001",
        name="Go golang.org/x/crypto DH",
        language="go",
        pattern=re.compile(r'\bdh\.NewX25519\s*\('),
        algorithm="DH",
        category="key_exchange",
        library="golang.org/x/crypto",
        confidence=0.85,
        purpose="key_exchange",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-TLS-001",
        name="Go tls.Config min version",
        language="go",
        pattern=re.compile(r'\btls\.(?:VersionTLS|Version)'),
        algorithm="TLS",
        category="protocol",
        library="crypto/tls",
        confidence=0.80,
        purpose="unknown",
        protocol="TLS",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-PBKDF2-001",
        name="Go x/crypto pbkdf2",
        language="go",
        pattern=re.compile(r'\bpbkdf2\.Key\s*\('),
        algorithm="PBKDF2",
        category="key_derivation",
        library="golang.org/x/crypto/pbkdf2",
        confidence=0.90,
        purpose="key_derivation",
    ),
    RegexRule(
        rule_id="GO-CRYPTO-SCRYPT-001",
        name="Go x/crypto scrypt",
        language="go",
        pattern=re.compile(r'\bscrypt\.Key\s*\('),
        algorithm="scrypt",
        category="key_derivation",
        library="golang.org/x/crypto/scrypt",
        confidence=0.90,
        purpose="key_derivation",
    ),

    # ═══════════════════════════════════════════════════════════════
    # RUST RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="RUST-RING-DIGEST-001",
        name="Rust ring::digest (SHA)",
        language="rust",
        pattern=re.compile(r'\bdigest::digest\s*\(\s*&digest::'),
        algorithm="SHA-256",
        category="hashing",
        library="ring",
        confidence=0.85,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="RUST-RING-SHA256-001",
        name="Rust ring SHA256 Algorithm",
        language="rust",
        pattern=re.compile(r'\bdigest::SHA256\b'),
        algorithm="SHA-256",
        category="hashing",
        library="ring",
        confidence=0.85,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="RUST-RING-SHA512-001",
        name="Rust ring SHA512",
        language="rust",
        pattern=re.compile(r'\bdigest::SHA512\b'),
        algorithm="SHA-512",
        category="hashing",
        library="ring",
        confidence=0.85,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="RUST-RING-RSA-001",
        name="Rust ring RSA key pair",
        language="rust",
        pattern=re.compile(r'\brsa::(?:RsaKeyPair|KeyPair)::from_pkcs8\s*\('),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="ring",
        confidence=0.85,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="RUST-RING-AEAD-AES-001",
        name="Rust ring AEAD AES-256-GCM",
        language="rust",
        pattern=re.compile(r'\baead::AES_256_GCM\b'),
        algorithm="AES",
        category="symmetric_encryption",
        library="ring",
        confidence=0.90,
        key_length=256,
        mode="GCM",
        purpose="encryption",
    ),
    RegexRule(
        rule_id="RUST-RING-AEAD-CHACHA-001",
        name="Rust ring AEAD ChaCha20-Poly1305",
        language="rust",
        pattern=re.compile(r'\baead::CHACHA20_POLY1305\b'),
        algorithm="ChaCha20",
        category="symmetric_encryption",
        library="ring",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="RUST-RING-HMAC-001",
        name="Rust ring HMAC",
        language="rust",
        pattern=re.compile(r'\bhmac::Key::new\s*\('),
        algorithm="HMAC",
        category="mac",
        library="ring",
        confidence=0.85,
        purpose="mac",
    ),
    RegexRule(
        rule_id="RUST-RING-PBKDF2-001",
        name="Rust ring PBKDF2",
        language="rust",
        pattern=re.compile(r'\bpbkdf2::derive\s*\('),
        algorithm="PBKDF2",
        category="key_derivation",
        library="ring",
        confidence=0.90,
        purpose="key_derivation",
    ),
    RegexRule(
        rule_id="RUST-RCG-AES-001",
        name="Rust RustCrypto aes crate",
        language="rust",
        pattern=re.compile(r'\bAes(?:128|256)(?:Gcm|Cbc|Ctr|Ecb)::new\s*\('),
        algorithm="AES",
        category="symmetric_encryption",
        library="RustCrypto",
        confidence=0.85,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="RUST-RCG-RSA-001",
        name="Rust RustCrypto RSA key gen",
        language="rust",
        pattern=re.compile(r'\bRsaPrivateKey::new\s*\('),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="RustCrypto/rsa",
        confidence=0.85,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="RUST-OPENSSL-RSA-001",
        name="Rust openssl RSA generate",
        language="rust",
        pattern=re.compile(r'\bRsa::generate\s*\('),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="openssl",
        confidence=0.85,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="RUST-ARGON2-001",
        name="Rust argon2 hash",
        language="rust",
        pattern=re.compile(r'\bArgon2::(?:hash_password|default)\s*\('),
        algorithm="Argon2",
        category="key_derivation",
        library="argon2",
        confidence=0.90,
        purpose="key_derivation",
    ),

    # ═══════════════════════════════════════════════════════════════
    # PHP RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="PHP-OPENSSL-ENCRYPT-001",
        name="PHP openssl_encrypt",
        language="php",
        pattern=re.compile(r'\bopenssl_encrypt\s*\('),
        algorithm="AES",
        category="symmetric_encryption",
        library="openssl",
        confidence=0.80,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PHP-OPENSSL-PKEY-001",
        name="PHP openssl_pkey_new",
        language="php",
        pattern=re.compile(r'\bopenssl_pkey_new\s*\('),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="openssl",
        confidence=0.80,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="PHP-OPENSSL-SIGN-001",
        name="PHP openssl_sign",
        language="php",
        pattern=re.compile(r'\bopenssl_sign\s*\('),
        algorithm="RSA",
        category="digital_signature",
        library="openssl",
        confidence=0.80,
        purpose="signing",
    ),
    RegexRule(
        rule_id="PHP-HASH-001",
        name="PHP hash() function",
        language="php",
        pattern=re.compile(r'\bhash\s*\(\s*["\']([^"\']+)["\']'),
        algorithm="SHA-256",  # Dynamically parsed
        category="hashing",
        library="php-hash",
        confidence=0.75,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PHP-HASH-HMAC-001",
        name="PHP hash_hmac()",
        language="php",
        pattern=re.compile(r'\bhash_hmac\s*\('),
        algorithm="HMAC",
        category="mac",
        library="php-hash",
        confidence=0.80,
        purpose="mac",
    ),
    RegexRule(
        rule_id="PHP-MD5-001",
        name="PHP md5()",
        language="php",
        pattern=re.compile(r'\bmd5\s*\('),
        algorithm="MD5",
        category="hashing",
        library="php-builtin",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PHP-SHA1-001",
        name="PHP sha1()",
        language="php",
        pattern=re.compile(r'\bsha1\s*\('),
        algorithm="SHA-1",
        category="hashing",
        library="php-builtin",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="PHP-SODIUM-001",
        name="PHP sodium_crypto_secretbox",
        language="php",
        pattern=re.compile(r'\bsodium_crypto_secretbox\s*\('),
        algorithm="ChaCha20",
        category="symmetric_encryption",
        library="libsodium",
        confidence=0.85,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="PHP-SODIUM-SIGN-001",
        name="PHP sodium_crypto_sign",
        language="php",
        pattern=re.compile(r'\bsodium_crypto_sign\s*\('),
        algorithm="Ed25519",
        category="digital_signature",
        library="libsodium",
        confidence=0.85,
        purpose="signing",
    ),
    RegexRule(
        rule_id="PHP-PASSWORD-HASH-001",
        name="PHP password_hash (Argon2/bcrypt)",
        language="php",
        pattern=re.compile(r'\bpassword_hash\s*\([^,]+,\s*(PASSWORD_(?:ARGON2I|ARGON2ID|BCRYPT|DEFAULT))'),
        algorithm="Argon2",  # Dynamically parsed from group 1
        category="key_derivation",
        library="php-builtin",
        confidence=0.85,
        purpose="key_derivation",
    ),
    RegexRule(
        rule_id="PHP-JWT-ENCODE-001",
        name="PHP JWT encode",
        language="php",
        pattern=re.compile(r'\bJWT::encode\s*\('),
        algorithm="JWT",
        category="protocol",
        library="firebase/php-jwt",
        confidence=0.80,
        purpose="signing",
        protocol="JWT",
    ),

    # ═══════════════════════════════════════════════════════════════
    # C# RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="CS-AES-CREATE-001",
        name="C# Aes.Create()",
        language="csharp",
        pattern=re.compile(r'\bAes\.Create\s*\(\s*\)'),
        algorithm="AES",
        category="symmetric_encryption",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="CS-RSA-CREATE-001",
        name="C# RSA.Create()",
        language="csharp",
        pattern=re.compile(r'\bRSA\.Create\s*\('),
        algorithm="RSA",
        category="asymmetric_encryption",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="CS-ECDSA-CREATE-001",
        name="C# ECDsa.Create()",
        language="csharp",
        pattern=re.compile(r'\bECDsa\.Create\s*\('),
        algorithm="ECDSA",
        category="digital_signature",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="signing",
    ),
    RegexRule(
        rule_id="CS-ECDH-CREATE-001",
        name="C# ECDiffieHellman.Create()",
        language="csharp",
        pattern=re.compile(r'\bECDiffieHellman\.Create\s*\('),
        algorithm="ECDH",
        category="key_exchange",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="key_exchange",
    ),
    RegexRule(
        rule_id="CS-SHA256-CREATE-001",
        name="C# SHA256.Create()",
        language="csharp",
        pattern=re.compile(r'\bSHA256(?:Managed)?\.Create\s*\(\s*\)'),
        algorithm="SHA-256",
        category="hashing",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="CS-SHA512-CREATE-001",
        name="C# SHA512.Create()",
        language="csharp",
        pattern=re.compile(r'\bSHA512(?:Managed)?\.Create\s*\(\s*\)'),
        algorithm="SHA-512",
        category="hashing",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="CS-SHA1-CREATE-001",
        name="C# SHA1.Create()",
        language="csharp",
        pattern=re.compile(r'\bSHA1(?:Managed)?\.Create\s*\(\s*\)'),
        algorithm="SHA-1",
        category="hashing",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="CS-MD5-CREATE-001",
        name="C# MD5.Create()",
        language="csharp",
        pattern=re.compile(r'\bMD5(?:CryptoServiceProvider)?\.Create\s*\(\s*\)'),
        algorithm="MD5",
        category="hashing",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="CS-HMACSHA256-001",
        name="C# HMACSHA256 new",
        language="csharp",
        pattern=re.compile(r'\bnew\s+HMACSHA(?:256|512|384)\s*\('),
        algorithm="HMAC",
        category="mac",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="mac",
    ),
    RegexRule(
        rule_id="CS-RIJNDAEL-001",
        name="C# RijndaelManaged (AES variant)",
        language="csharp",
        pattern=re.compile(r'\bnew\s+RijndaelManaged\s*\(\s*\)'),
        algorithm="AES",
        category="symmetric_encryption",
        library="System.Security.Cryptography",
        confidence=0.85,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="CS-DES-CREATE-001",
        name="C# DES.Create()",
        language="csharp",
        pattern=re.compile(r'\bDES\.Create\s*\(\s*\)'),
        algorithm="DES",
        category="symmetric_encryption",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="CS-3DES-CREATE-001",
        name="C# TripleDES.Create()",
        language="csharp",
        pattern=re.compile(r'\bTripleDES\.Create\s*\(\s*\)'),
        algorithm="3DES",
        category="symmetric_encryption",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="CS-PBKDF2-001",
        name="C# Rfc2898DeriveBytes (PBKDF2)",
        language="csharp",
        pattern=re.compile(r'\bnew\s+Rfc2898DeriveBytes\s*\('),
        algorithm="PBKDF2",
        category="key_derivation",
        library="System.Security.Cryptography",
        confidence=0.90,
        purpose="key_derivation",
    ),

    # ═══════════════════════════════════════════════════════════════
    # KOTLIN RULES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="KT-JCE-CIPHER-001",
        name="Kotlin Cipher.getInstance",
        language="kotlin",
        pattern=re.compile(r'\bCipher\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="AES",  # Dynamically parsed
        category="symmetric_encryption",
        library="javax.crypto",
        confidence=0.80,
        purpose="encryption",
    ),
    RegexRule(
        rule_id="KT-JCE-KEYPAIRGEN-001",
        name="Kotlin KeyPairGenerator.getInstance",
        language="kotlin",
        pattern=re.compile(r'\bKeyPairGenerator\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="RSA",  # Dynamically parsed
        category="asymmetric_encryption",
        library="java.security",
        confidence=0.80,
        purpose="key_generation",
    ),
    RegexRule(
        rule_id="KT-JCE-MESSAGEDIGEST-001",
        name="Kotlin MessageDigest.getInstance",
        language="kotlin",
        pattern=re.compile(r'\bMessageDigest\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="SHA-256",  # Dynamically parsed
        category="hashing",
        library="java.security",
        confidence=0.80,
        purpose="hashing",
    ),
    RegexRule(
        rule_id="KT-JCE-SIGNATURE-001",
        name="Kotlin Signature.getInstance",
        language="kotlin",
        pattern=re.compile(r'\bSignature\.getInstance\s*\(\s*"([^"]+)"\s*\)'),
        algorithm="Signature",
        category="digital_signature",
        library="java.security",
        confidence=0.80,
        purpose="signing",
    ),
    RegexRule(
        rule_id="KT-JCE-MAC-001",
        name="Kotlin Mac.getInstance (HMAC)",
        language="kotlin",
        pattern=re.compile(r'\bMac\.getInstance\s*\(\s*"(Hmac[A-Z0-9]+)"\s*\)'),
        algorithm="HMAC",
        category="mac",
        library="javax.crypto",
        confidence=0.80,
        purpose="mac",
    ),
    RegexRule(
        rule_id="KT-BOUNCY-AES-001",
        name="Kotlin BouncyCastle AES engine",
        language="kotlin",
        pattern=re.compile(r'\bAESEngine\s*\(\s*\)'),
        algorithm="AES",
        category="symmetric_encryption",
        library="BouncyCastle",
        confidence=0.80,
        purpose="encryption",
    ),

    # ═══════════════════════════════════════════════════════════════
    # CONFIGURATION / STRUCTURED FILES
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="CFG-TLS-MIN-VERSION-001",
        name="Config TLS minimum version specification",
        language="config",
        pattern=re.compile(r'(?:tls_min(?:imum)?_version|ssl_protocols?|minProtocol)\s*[=:]\s*["\']?(TLS(?:v1|1\.[0-3])|SSLv\d)["\']?', re.IGNORECASE),
        algorithm="TLS",
        category="protocol",
        library="config",
        confidence=0.75,
        purpose="unknown",
        protocol="TLS",
    ),
    RegexRule(
        rule_id="CFG-TLS-CIPHER-001",
        name="Config TLS cipher suite specification",
        language="config",
        pattern=re.compile(r'(?:ssl_ciphers?|tls_ciphers?|cipher_suites?)\s*[=:]\s*["\']?([A-Z][A-Z0-9_:-]+)["\']?', re.IGNORECASE),
        algorithm="TLS",
        category="protocol",
        library="config",
        confidence=0.70,
        purpose="unknown",
        protocol="TLS",
    ),
    RegexRule(
        rule_id="CFG-JWT-SECRET-001",
        name="Config JWT secret",
        language="config",
        pattern=re.compile(r'(?:jwt_secret|JWT_SECRET|jwt_signing_key|JWT_SIGNING_KEY)\s*[=:]\s*["\']?([^\s"\']{12,})["\']?'),
        algorithm="JWT",
        category="protocol",
        library="config",
        confidence=0.75,
        purpose="signing",
        protocol="JWT",
    ),
    RegexRule(
        rule_id="CFG-SSH-KEY-TYPE-001",
        name="Config SSH key type specification",
        language="config",
        pattern=re.compile(r'(?:HostKey|IdentityFile|ssh_host_(?:rsa|ecdsa|ed25519)_key)', re.IGNORECASE),
        algorithm="SSH",
        category="protocol",
        library="config",
        confidence=0.70,
        purpose="unknown",
        protocol="SSH",
    ),

    # ═══════════════════════════════════════════════════════════════
    # ALL / PEM MARKERS (unchanged from original, updated rule IDs)
    # ═══════════════════════════════════════════════════════════════
    RegexRule(
        rule_id="PEM-RSA-PRIVATE-KEY-001",
        name="PEM RSA Private Key Header",
        language="all",
        pattern=re.compile(r"-----BEGIN RSA PRIVATE KEY-----"),
        algorithm="RSA",
        category="certificate_or_key",
        library="PEM",
        confidence=0.90,
        purpose="unknown",
    ),
    RegexRule(
        rule_id="PEM-EC-PRIVATE-KEY-001",
        name="PEM EC Private Key Header",
        language="all",
        pattern=re.compile(r"-----BEGIN EC PRIVATE KEY-----"),
        algorithm="ECC",
        category="certificate_or_key",
        library="PEM",
        confidence=0.90,
        purpose="unknown",
    ),
    RegexRule(
        rule_id="PEM-PRIVATE-KEY-PKCS8-001",
        name="PEM PKCS8 Private Key Header",
        language="all",
        pattern=re.compile(r"-----BEGIN PRIVATE KEY-----"),
        algorithm="RSA",
        category="certificate_or_key",
        library="PEM",
        confidence=0.85,
        purpose="unknown",
    ),
    RegexRule(
        rule_id="PEM-CERTIFICATE-001",
        name="PEM Certificate Header",
        language="all",
        pattern=re.compile(r"-----BEGIN CERTIFICATE-----"),
        algorithm="Certificate",
        category="certificate_or_key",
        library="PEM",
        confidence=0.90,
        purpose="unknown",
    ),
    RegexRule(
        rule_id="PEM-CERTIFICATE-REQUEST-001",
        name="PEM Certificate Signing Request",
        language="all",
        pattern=re.compile(r"-----BEGIN CERTIFICATE REQUEST-----"),
        algorithm="Certificate",
        category="certificate_or_key",
        library="PEM",
        confidence=0.90,
        purpose="unknown",
    ),
    RegexRule(
        rule_id="PEM-PUBLIC-KEY-001",
        name="PEM Public Key Header",
        language="all",
        pattern=re.compile(r"-----BEGIN PUBLIC KEY-----"),
        algorithm="RSA",
        category="certificate_or_key",
        library="PEM",
        confidence=0.85,
        purpose="unknown",
    ),
    RegexRule(
        rule_id="PEM-DSA-PRIVATE-KEY-001",
        name="PEM DSA Private Key Header",
        language="all",
        pattern=re.compile(r"-----BEGIN DSA PRIVATE KEY-----"),
        algorithm="DSA",
        category="certificate_or_key",
        library="PEM",
        confidence=0.90,
        purpose="unknown",
    ),
    RegexRule(
        rule_id="PEM-ED25519-PRIVATE-KEY-001",
        name="PEM Ed25519 Private Key Header",
        language="all",
        pattern=re.compile(r"-----BEGIN OPENSSH PRIVATE KEY-----"),
        algorithm="Ed25519",
        category="certificate_or_key",
        library="PEM",
        confidence=0.85,
        purpose="unknown",
    ),
]

# Build a backward-compatible lookup from old rule IDs to new ones
# (legacy IDs from existing code that calls rules by ID)
LEGACY_RULE_ID_MAP = {
    "py-hashlib-md5": "PY-HASHLIB-MD5-001",
    "py-hashlib-sha1": "PY-HASHLIB-SHA1-001",
    "py-hashlib-sha256": "PY-HASHLIB-SHA256-001",
    "py-hashlib-sha512": "PY-HASHLIB-SHA512-001",
    "py-hashlib-sha3": "PY-HASHLIB-SHA3-001",
    "py-crypto-rsa-gen": "PY-PYCRYPTO-RSA-GENERATE-001",
    "py-crypto-aes-new": "PY-PYCRYPTO-AES-NEW-001",
    "py-cryptography-sha1": "PY-CRYPTOGRAPHY-SHA1-001",
    "py-cryptography-sha256": "PY-CRYPTOGRAPHY-SHA256-001",
    "py-cryptography-mode-cbc": "PY-CRYPTOGRAPHY-CBC-001",
    "py-cryptography-mode-gcm": "PY-CRYPTOGRAPHY-GCM-001",
    "java-cipher-instance": "JAVA-JCE-CIPHER-001",
    "java-keypair-gen": "JAVA-JCE-KEYPAIRGEN-001",
    "java-message-digest": "JAVA-JCE-MESSAGEDIGEST-001",
    "java-signature-instance": "JAVA-JCE-SIGNATURE-001",
    "java-keyagreement-instance": "JAVA-JCE-KEYAGREEMENT-001",
    "java-hardcoded-secret-string": "JAVA-HARDCODED-SECRET-001",
    "c-openssl-rsa-gen": "C-OPENSSL-RSA-GENERATE-001",
    "c-openssl-evp-aes128-cbc": "C-OPENSSL-AES128-CBC-001",
    "c-openssl-evp-aes256-gcm": "C-OPENSSL-AES256-GCM-001",
    "c-openssl-evp-sha256": "C-OPENSSL-SHA256-001",
    "c-openssl-evp-sha1": "C-OPENSSL-SHA1-001",
    "c-openssl-evp-md5": "C-OPENSSL-MD5-001",
    "c-openssl-ec-new": "C-OPENSSL-EC-NEW-001",
    "c-openssl-dh-new": "C-OPENSSL-DH-NEW-001",
    "c-openssl-dsa-new": "C-OPENSSL-DSA-NEW-001",
    "c-hardcoded-secret-string": "C-HARDCODED-SECRET-001",
    "pem-rsa-private-key": "PEM-RSA-PRIVATE-KEY-001",
    "pem-ec-private-key": "PEM-EC-PRIVATE-KEY-001",
    "pem-certificate": "PEM-CERTIFICATE-001",
}
